baseURL = "https://monpearte.com.au/"
languageCode = "en-us"
title = "Monpearte IT Solutions - IT Solutions for the Central and Far West of NSW"
theme = "hugo-initio"
publishDir = "public"
enableRobotsTXT = "true"

[params]
    name = "Monpearte IT Solutions"
    description = "IT Solutions for the Central and Far West NSW"
    year = 2017
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = true
    showRecentWorks = false
    showDownload = false
    showClients = false

    footerEnableContact = false
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "UA-123121596-2"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/monpearteIT"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/monpearteIT"
    icon = "fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/company/monpearte-it-solutions/"
    icon = "fa-linkedin-square"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "email"
	url = "mailto:info@monpearte.com.au"
    icon = "fa-envelope"
    footer = true
    sharethis = true
    network = "email"
